### ISSUE TITLE
启动不起来

### ISSUE THREAD

**Issue by cheng69** [BiYuqi/vue-admin-template#1]

**Comment by BiYuqi** [comment]
- 报错信息?
- 如何启动的，需要起服务端.

**Comment by BiYuqi** [comment]
@cheng69 
- 你先更新下代码， 执行`npm run server`, 刚更新了README， 增加了起服务命令[package.json](https://github.com/BiYuqi/vue-admin-template/blob/master/package.json#L10)
- 如果不更新最新代码，命令行执行 `cd ./server && node app.js`

**Comment by BiYuqi** [comment]
@cheng69 本地run `npm run dev` 之前，需要把server启动

**Comment by cheng69** [comment]
好的谢谢，明天试一试

**Comment by BiYuqi** [comment]
@cheng69 是否可行? 如果没问题，我就关闭了
